version: '3.4'

services:
  zoekt-webserver:
    build:
      context: ..
      dockerfile: ./Dockerfile
      network: host
    image: zoekt-webserver
    container_name: zoekt-webserver
    hostname: zoekt-webserver
    volumes:
      - "./dev:/demo"
    working_dir: /demo
    stdin_open: true
    tty: true